[project]
name = "distrobox-boost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xz-dev", email = "xiangzhedev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.0.0",
]

[project.scripts]
distrobox-boost = "distrobox_boost:main"

[dependency-groups]
dev = ["pytest>=8.0.0"]

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
